#!/usr/bin/env bash
# One-touch differential runner.
#   difftest/run.sh                 -> build + run every scenario, print a summary
#   difftest/run.sh scripts/NN.script -> build + run one scenario, print its diff
#
# Layout (all paths relative to this script):
#   vendor/etcd-raft   pristine etcd-io/raft@26647d5 (git submodule)
#   harness_export.go  the ONLY file we overlay onto that pinned checkout
#   go-harness         Go driver over etcd RawNode -> normalized JSON trace
#   mbt-harness        MoonBit driver (moon package) -> same schema
#   scripts            DSL scenarios
set -e
DT="$(cd "$(dirname "$0")" && pwd)"
ROOT="$(cd "$DT/.." && pwd)"
export PATH="$HOME/.moon/bin:$PATH"
export GOTOOLCHAIN=auto GOPROXY=https://goproxy.cn,direct

# Lay our single overlay file over the pinned submodule, then build the Go side.
cp "$DT/harness_export.go" "$DT/vendor/etcd-raft/harness_export.go"
( cd "$DT/go-harness" && go build -o harness.exe . )

mkdir -p "$DT/traces"

run_one() {
  local script="$1"
  local base
  base="$(basename "$script" .script)"
  {
    echo "// GENERATED by run.sh. Do not edit."
    echo "///|"
    echo "let script : String ="
    while IFS= read -r line || [ -n "$line" ]; do
      printf '  #|%s\n' "$line"
    done < "$script"
  } > "$DT/mbt-harness/script_gen.mbt"
  "$DT/go-harness/harness.exe" "$script" 2>/dev/null > "$DT/traces/${base}.go.jsonl"
  ( cd "$ROOT" && moon run difftest/mbt-harness 2>/dev/null ) > "$DT/traces/${base}.mb.jsonl"
  python "$DT/diff.py" "$DT/traces/${base}.go.jsonl" "$DT/traces/${base}.mb.jsonl" "$base"
}

if [ -n "$1" ]; then
  run_one "$DT/$1"
else
  for s in "$DT"/scripts/*.script; do
    run_one "$s" | head -1
  done
fi
